dist: xenial
matrix:
  include:
    - language: python
      python: 
        - 3.7
      install:
        - export CXX="g++-7" CC="gcc-7" 
        - pip install ./dgemmPy
      script:
        - pytest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenblas-base libopenblas-dev gcc-7 g++-7 gfortran-7

notifications:
  email: false